<?php
/**
 * @file
 * This module hides disabled menu items in the menu interface within node edit
 */


/**
 * Implements hook_form_FORM_ID_alter().
 */
function hide_disabled_menu_items_form_node_form_alter(&$form, &$form_state, $form_id) {

  // Get all current menu items
  $options = $form['menu']['link']['parent']['#options'];

  // Take out all disabled menu items
  foreach ($options as $key=>$link_name) {
    	if (strpos($link_name, '(disabled)') == FALSE) {
		$options_enabled[$key] = $link_name;
	}
  }
  $options = $options_enabled;

  // Put new list of menu items without the disabled items into the parent menu select box
  $form['menu']['link']['parent']['#options'] = $options;

}
